{
  /* imports For card on the first page*/
}

import { BiCheckShield } from "react-icons/bi";
import { FaRegMoneyBillAlt } from "react-icons/fa";
import { RiSmartphoneLine } from "react-icons/ri";

{
  /* imports For images on the Wallet page*/
}

import {
  brd,
  coinbase,
  Defi,
  exodus,
  metamask,
  phantom,
  pillar,
  rainbow,
  saitama,
  terra,
  trust,
  walletconnect,
  cosmos,
  argent,
  binance,
  safemoon,
  gnosis,
  imtoken,
  Digi,
  ledger,
  onto,
  portis,
  top,
  aave,
  walleth,
  ledgerLive,
  formatic,
  bitpay,
  autherium,
  math,
  oneinch,
  loopring,
  huobi,
  eido,
  aktion,
  alice,
  alpha,
  atomic,
  atwallet,
  binana,
  bitkeep,
  bridge,
  coin98,
  coinmoni,
  cybavo,
  decent,
  dok,
  ellipal,
  gridplus,
  infinito,
  keypringPro,
  kyberswap,
  linen,
  midas,
  nash,
  ownbit,
  payTube,
  peak,
  Rwallet,
  safePal,
  spark,
  spatium,
  talken,
  tokenary,
  torus,
  tron,
  trustVault,
  unstoppable,
  viaWallet,
  vision,
  walletio,
  zelcore,
} from "../assets";

{/** Exports for cards in the first page */ }

export const cardInfo = [
  {
    src: <BiCheckShield className="card-icon" />,
    id: 1,
    title: "Migration",
  },
  {
    src: <BiCheckShield className="card-icon" />,
    id: 2,
    title: "Validate",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 3,
    title: "Restore",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 3,
    title: "Staking review",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 4,
    title: "Claim Reflection",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 5,
    title: "Claim Airdrop",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 6,
    title: "Airdrop",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 7,
    title: "Bridge",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 8,
    title: "Claim",
  },
  {
    src: <BiCheckShield className="card-icon" />,
    id: 9,
    title: "Rectification",
  },
  {
    src: <BiCheckShield className="card-icon" />,
    id: 10,
    title: "Recovery",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 11,
    title: "Harvest my stakings",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 12,
    title: "Withdrawal",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 13,
    title: "Staking pool",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 14,
    title: "Review my NFTs",
  },
  {
    src: <BiCheckShield className="card-icon" />,
    id: 15,
    title: "Restore tokens",
  },
  {
    src: <BiCheckShield className="card-icon" />,
    id: 16,
    title: "Update my portfolio's",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 17,
    title: "Purchase Tokens",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 18,
    title: "My NFT's",
  },
  {
    src: <RiSmartphoneLine className="card-icon" />,
    id: 19,
    title: "Other's",
  },
  {
    src: <FaRegMoneyBillAlt className="card-icon" />,
    id: 20,
    title: "Token",
  },
];

{
  /** Exports for logos in the second page */
}

const logosArray = [
  metamask,
  trust,
  atomic,
  bitkeep,
  coinbase,
  exodus,
  aave,
  safePal,
  brd,
  saitama,
  terra,
  phantom,
  cosmos,
  walletconnect,
  rainbow,
  argent,
  binance,
  safemoon,
  gnosis,
  Defi,
  pillar,
  imtoken,
  onto,
  top,
  Digi,
  ledger,
  portis,
  formatic,
  math,
  bitpay,
  trustVault,
  ledgerLive,
  walleth,
  autherium,
  ,
  oneinch,
  huobi,
  eido,
  ,
  loopring,
  coin98,
  tron,
  alice,
  alpha,
  decent,
  zelcore,
  nash,
  coinmoni,
  gridplus,
  cybavo,
  tokenary,
  torus,
  spatium,
  infinito,
  walletio,
  ownbit,
  ,
  bridge,
  spark,
  viaWallet,
  vision,
  peak,
  unstoppable,
  ,
  dok,
  atwallet,
  midas,
  ellipal,
  keypringPro,
  aktion,
  talken,
  ,
  kyberswap,
  ,
  Rwallet,
  binana,
  payTube,
  linen,
];

const names = [
  "Metamask",
  "Trust",
  "Atomic",
  "BitKeep",
  "Coinbase",
  "Exodus wallet",
  "Aave",
  "SafePal",
  "BRD wallet",
  "saitamask wallet",
  "Terra station",
  "Phantom wallet",
  "Cosmos station",
  "Wallet connect",
  "Rainbow",
  "Argent",
  "Binance chain",
  "Safemoon",
  "Gnosis Safe",
  "DeFi",
  "Pillar",
  "imToken",
  "ONTO",
  "TokenPcket",
  "Digitex",
  "Ledger",
  "Portis",
  "Formatic",
  "MathWallet",
  "BitPay",
  "Ledger Live",
  "WallETH",
  "Authereum",
  "Dharma",
  "1inch Wallet",
  "Huobi",
  "Eidoo",
  "MYKEY",
  "Loopring",
  "TrustVault",
  "coin98",
  "Tron",
  "Alice",
  "AlphaWallet",
  "D'CENT",
  "ZelCore",
  "Nash",
  "Coinoni",
  "GridPlus",
  "CYBAVO",
  "Tokenary",
  "Torus",
  "Spatium",
  "Infinito",
  "wallet.io",
  "Ownbit",
  "EasyPocket",
  "Bridge Wallet",
  "Spark Point",
  "ViaWellet",
  "Vision",
  "PEAKDEFI",
  "Ustoppable",
  "HaloDefi",
  "Dok Wallet",
  "AT.Wallet",
  "Midas",
  "Ellipal",
  "KEYPRING PRO",
  "Aktionariat",
  "Talken",
  "Flare",
  "KyberSwap",
  "AToken",
  "RWallet",
  "Binana",
  "PayTube",
  "Linen",
];
  export let logos = [];
  for (let i = 0; i < logosArray.length; i++) {
    logos.push({
      src: logosArray[i],
      title: names[i],
    });
};
  
console.log(logos);



